import { Business, Category, City, Deal, Event } from './types';

export const CITIES: City[] = [
  { id: 'baghdad', nameEn: 'Baghdad', nameAr: 'بغداد', emoji: '🏰', region: 'Central' },
  { id: 'erbil', nameEn: 'Erbil', nameAr: 'أربيل', emoji: '🏔️', region: 'Kurdistan' },
  { id: 'sulaymaniyah', nameEn: 'Sulaymaniyah', nameAr: 'السليمانية', emoji: '⛰️', region: 'Kurdistan' },
  { id: 'basra', nameEn: 'Basra', nameAr: 'البصرة', emoji: '⚓', region: 'South' },
  { id: 'mosul', nameEn: 'Mosul', nameAr: 'الموصل', emoji: '🌉', region: 'North' },
  { id: 'kirkuk', nameEn: 'Kirkuk', nameAr: 'كركوك', emoji: '🔥', region: 'North' },
  { id: 'najaf', nameEn: 'Najaf', nameAr: 'النجف', emoji: '🕌', region: 'Central' },
  { id: 'karbala', nameEn: 'Karbala', nameAr: 'كربلاء', emoji: '🕌', region: 'Central' },
];

export const CATEGORIES: Category[] = [
  { id: 'restaurants', nameEn: 'Restaurants', nameAr: 'مطاعم', emoji: '🍽️', color: '#C1440E' },
  { id: 'cafes', nameEn: 'Cafes', nameAr: 'مقاهي', emoji: '☕', color: '#C9A84C' },
  { id: 'tech', nameEn: 'Tech', nameAr: 'تكنولوجيا', emoji: '💻', color: '#1A2340' },
  { id: 'legal', nameEn: 'Legal', nameAr: 'قانون', emoji: '⚖️', color: '#2D7A4F' },
  { id: 'healthcare', nameEn: 'Healthcare', nameAr: 'رعاية صحية', emoji: '🏥', color: '#C1440E' },
  { id: 'finance', nameEn: 'Finance', nameAr: 'تمويل', emoji: '💰', color: '#2D7A4F' },
  { id: 'realestate', nameEn: 'Real Estate', nameAr: 'عقارات', emoji: '🏢', color: '#1A2340' },
  { id: 'education', nameEn: 'Education', nameAr: 'تعليم', emoji: '📚', color: '#C9A84C' },
  { id: 'transport', nameEn: 'Transport', nameAr: 'نقل', emoji: '🚗', color: '#2D7A4F' },
  { id: 'shopping', nameEn: 'Shopping', nameAr: 'تسوق', emoji: '🛍️', color: '#C1440E' },
  { id: 'hotels', nameEn: 'Hotels', nameAr: 'فنادق', emoji: '🏨', color: '#1A2340' },
  { id: 'entertainment', nameEn: 'Entertainment', nameAr: 'ترفيه', emoji: '🎭', color: '#C9A84C' },
];

export const BUSINESSES: Business[] = [
  {
    id: '1',
    nameEn: 'Al-Mansour Grill',
    nameAr: 'مشويات المنصور',
    category: 'restaurants',
    city: 'baghdad',
    phone: '+964 770 123 4567',
    rating: 4.8,
    reviewCount: 520,
    description: 'Traditional Iraqi grills and masgouf in the heart of Baghdad.',
    isVerified: true,
    isFeatured: true,
    imageEmoji: '🍢',
    priceRange: 'mid',
  },
  {
    id: '2',
    nameEn: 'Erbil Citadel Cafe',
    nameAr: 'مقهى قلعة أربيل',
    category: 'cafes',
    city: 'erbil',
    phone: '+964 750 987 6543',
    rating: 4.9,
    reviewCount: 840,
    description: 'Historic cafe with a stunning view of the Erbil Citadel.',
    isVerified: true,
    isFeatured: true,
    imageEmoji: '☕',
    priceRange: 'budget',
  },
  {
    id: '3',
    nameEn: 'Basra Port Hotel',
    nameAr: 'فندق ميناء البصرة',
    category: 'hotels',
    city: 'basra',
    phone: '+964 780 111 2222',
    rating: 4.5,
    reviewCount: 310,
    description: 'Luxury stay with panoramic views of the Shatt al-Arab.',
    isVerified: true,
    isFeatured: false,
    imageEmoji: '🏨',
    priceRange: 'premium',
  },
  {
    id: '4',
    nameEn: 'Babylon Tech Solutions',
    nameAr: 'حلول بابل التقنية',
    category: 'tech',
    city: 'baghdad',
    phone: '+964 790 333 4444',
    rating: 4.7,
    reviewCount: 150,
    description: 'Leading software development and IT consultancy in Iraq.',
    isVerified: true,
    isFeatured: false,
    imageEmoji: '💻',
    priceRange: 'mid',
  },
  {
    id: '5',
    nameEn: 'Sulaymaniyah Heights Real Estate',
    nameAr: 'عقارات مرتفعات السليمانية',
    category: 'realestate',
    city: 'sulaymaniyah',
    phone: '+964 771 555 6666',
    rating: 4.6,
    reviewCount: 95,
    description: 'Premium residential and commercial properties in the mountains.',
    isVerified: false,
    isFeatured: true,
    imageEmoji: '🏢',
    priceRange: 'premium',
  },
  {
    id: '6',
    nameEn: 'Mosul Heritage Restaurant',
    nameAr: 'مطعم تراث الموصل',
    category: 'restaurants',
    city: 'mosul',
    phone: '+964 751 777 8888',
    rating: 4.4,
    reviewCount: 210,
    description: 'Authentic Moslawi cuisine and traditional hospitality.',
    isVerified: true,
    isFeatured: false,
    imageEmoji: '🥘',
    priceRange: 'mid',
  },
  {
    id: '7',
    nameEn: 'Najaf Legal Partners',
    nameAr: 'شركاء النجف للقانون',
    category: 'legal',
    city: 'najaf',
    phone: '+964 781 999 0000',
    rating: 4.9,
    reviewCount: 65,
    description: 'Expert legal advice and corporate law services.',
    isVerified: true,
    isFeatured: false,
    imageEmoji: '⚖️',
    priceRange: 'premium',
  },
  {
    id: '8',
    nameEn: 'Karbala Education Center',
    nameAr: 'مركز كربلاء التعليمي',
    category: 'education',
    city: 'karbala',
    phone: '+964 791 222 3333',
    rating: 4.7,
    reviewCount: 180,
    description: 'Language courses and professional development training.',
    isVerified: true,
    isFeatured: false,
    imageEmoji: '📚',
    priceRange: 'budget',
  },
  {
    id: '9',
    nameEn: 'Kirkuk Energy Finance',
    nameAr: 'تمويل كركوك للطاقة',
    category: 'finance',
    city: 'kirkuk',
    phone: '+964 772 444 5555',
    rating: 4.3,
    reviewCount: 45,
    description: 'Financial planning and investment services for the energy sector.',
    isVerified: false,
    isFeatured: false,
    imageEmoji: '💰',
    priceRange: 'premium',
  },
  {
    id: '10',
    nameEn: 'Baghdad Central Clinic',
    nameAr: 'عيادة بغداد المركزية',
    category: 'healthcare',
    city: 'baghdad',
    phone: '+964 773 666 7777',
    rating: 4.8,
    reviewCount: 420,
    description: 'Multi-specialty medical center with modern facilities.',
    isVerified: true,
    isFeatured: true,
    imageEmoji: '🏥',
    priceRange: 'mid',
  },
  {
    id: '11',
    nameEn: 'Erbil Mall Shopping',
    nameAr: 'تسوق أربيل مول',
    category: 'shopping',
    city: 'erbil',
    phone: '+964 752 888 9999',
    rating: 4.6,
    reviewCount: 1200,
    description: 'The ultimate shopping destination with international brands.',
    isVerified: true,
    isFeatured: false,
    imageEmoji: '🛍️',
    priceRange: 'mid',
  },
  {
    id: '12',
    nameEn: 'Basra Express Transport',
    nameAr: 'نقل البصرة السريع',
    category: 'transport',
    city: 'basra',
    phone: '+964 782 000 1111',
    rating: 4.2,
    reviewCount: 280,
    description: 'Reliable logistics and passenger transport across Iraq.',
    isVerified: false,
    isFeatured: false,
    imageEmoji: '🚗',
    priceRange: 'budget',
  },
  {
    id: '13',
    nameEn: 'Sulaymaniyah Cinema Park',
    nameAr: 'سينما بارك السليمانية',
    category: 'entertainment',
    city: 'sulaymaniyah',
    phone: '+964 774 222 3333',
    rating: 4.7,
    reviewCount: 560,
    description: 'Modern cinema complex showing the latest global releases.',
    isVerified: true,
    isFeatured: false,
    imageEmoji: '🎭',
    priceRange: 'mid',
  },
  {
    id: '14',
    nameEn: 'Mosul Tech Hub',
    nameAr: 'مركز الموصل التقني',
    category: 'tech',
    city: 'mosul',
    phone: '+964 753 444 5555',
    rating: 4.5,
    reviewCount: 88,
    description: 'Co-working space and incubator for tech startups.',
    isVerified: true,
    isFeatured: true,
    imageEmoji: '💻',
    priceRange: 'budget',
  },
  {
    id: '15',
    nameEn: 'Baghdad Riverside Cafe',
    nameAr: 'مقهى ضفاف بغداد',
    category: 'cafes',
    city: 'baghdad',
    phone: '+964 792 666 7777',
    rating: 4.6,
    reviewCount: 340,
    description: 'Relaxing atmosphere with traditional tea and shisha.',
    isVerified: true,
    isFeatured: false,
    imageEmoji: '☕',
    priceRange: 'budget',
  },
  {
    id: '16',
    nameEn: 'Erbil Grand Hotel',
    nameAr: 'فندق أربيل الكبير',
    category: 'hotels',
    city: 'erbil',
    phone: '+964 754 888 9999',
    rating: 4.9,
    reviewCount: 670,
    description: 'Five-star luxury in the heart of the business district.',
    isVerified: true,
    isFeatured: true,
    imageEmoji: '🏨',
    priceRange: 'premium',
  },
  {
    id: '17',
    nameEn: 'Najaf Book House',
    nameAr: 'دار كتب النجف',
    category: 'education',
    city: 'najaf',
    phone: '+964 783 000 1111',
    rating: 4.8,
    reviewCount: 120,
    description: 'Extensive collection of academic and religious literature.',
    isVerified: true,
    isFeatured: false,
    imageEmoji: '📚',
    priceRange: 'budget',
  },
  {
    id: '18',
    nameEn: 'Karbala Family Restaurant',
    nameAr: 'مطعم عائلة كربلاء',
    category: 'restaurants',
    city: 'karbala',
    phone: '+964 793 222 3333',
    rating: 4.5,
    reviewCount: 410,
    description: 'Spacious dining for families with a diverse menu.',
    isVerified: true,
    isFeatured: false,
    imageEmoji: '🍽️',
    priceRange: 'mid',
  },
  {
    id: '19',
    nameEn: 'Basra Business Center',
    nameAr: 'مركز أعمال البصرة',
    category: 'finance',
    city: 'basra',
    phone: '+964 784 444 5555',
    rating: 4.4,
    reviewCount: 75,
    description: 'Professional office spaces and financial consulting.',
    isVerified: true,
    isFeatured: false,
    imageEmoji: '🏢',
    priceRange: 'premium',
  },
  {
    id: '20',
    nameEn: 'Sulaymaniyah Art Gallery',
    nameAr: 'معرض فنون السليمانية',
    category: 'entertainment',
    city: 'sulaymaniyah',
    phone: '+964 775 666 7777',
    rating: 4.9,
    reviewCount: 130,
    description: 'Showcasing contemporary Kurdish and Iraqi artists.',
    isVerified: true,
    isFeatured: true,
    imageEmoji: '🎨',
    priceRange: 'mid',
  },
];

export const DEALS: Deal[] = [
  { id: 'd1', businessId: '1', title: 'Family Dinner Special', discount: '20%', expiresAt: '2026-04-01' },
  { id: 'd2', businessId: '2', title: 'Morning Coffee Deal', discount: '15%', expiresAt: '2026-03-25' },
  { id: 'd3', businessId: '11', title: 'Weekend Sale', discount: '30%', expiresAt: '2026-03-20' },
  { id: 'd4', businessId: '16', title: 'Early Bird Booking', discount: '25%', expiresAt: '2026-05-10' },
  { id: 'd5', businessId: '6', title: 'Traditional Lunch Set', discount: '10%', expiresAt: '2026-03-30' },
  { id: 'd6', businessId: '13', title: 'Student Movie Night', discount: '50%', expiresAt: '2026-04-15' },
];

export const EVENTS: Event[] = [
  { id: 'e1', title: 'Baghdad International Fair', titleAr: 'معرض بغداد الدولي', city: 'baghdad', date: 'Oct 15, 2026', category: 'Business', emoji: '🎪' },
  { id: 'e2', title: 'Erbil Spring Festival', titleAr: 'مهرجان ربيع أربيل', city: 'erbil', date: 'Mar 21, 2026', category: 'Culture', emoji: '🌸' },
  { id: 'e3', title: 'Basra Poetry Evening', titleAr: 'أمسية البصرة الشعرية', city: 'basra', date: 'Apr 05, 2026', category: 'Arts', emoji: '📜' },
  { id: 'e4', title: 'Sulaymaniyah Tech Summit', titleAr: 'قمة السليمانية للتقنية', city: 'sulaymaniyah', date: 'May 12, 2026', category: 'Tech', emoji: '🚀' },
  { id: 'e5', title: 'Mosul Heritage Day', titleAr: 'يوم تراث الموصل', city: 'mosul', date: 'Jun 10, 2026', category: 'History', emoji: '🏺' },
  { id: 'e6', title: 'Najaf Calligraphy Workshop', titleAr: 'ورشة خط النجف', city: 'najaf', date: 'Jul 22, 2026', category: 'Arts', emoji: '🖋️' },
  { id: 'e7', title: 'Karbala Religious Tourism Forum', titleAr: 'منتدى السياحة الدينية بكربلاء', city: 'karbala', date: 'Aug 15, 2026', category: 'Tourism', emoji: '🕌' },
  { id: 'e8', title: 'Kirkuk Cultural Exchange', titleAr: 'تبادل كركوك الثقافي', city: 'kirkuk', date: 'Sep 05, 2026', category: 'Culture', emoji: '🤝' },
];
